apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/kubeaid.git
      path: argocd-helm-charts/argo-cd
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kcm/argocd-apps/values-argo-cd.yaml
    - repoURL: https://github.com/ashish1099/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
