apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgALbUuBXmG6y/O8hruDQio1NSQ5s2hCMWCUFnmcyTEGWH56QYG0pGfpdnDQ/4TNnhgY7PHOh778+C1qs6mneykSSxCiArZOjNVmQdh2dHGIP3J/m1BCmA5s8fBPN6+0goOzycfLIbxDZTVV20L0tYmO6XP+Sg7k4etpNk4BCovJLAby6R/Rn8iIjhUeyaHI9I+jTNu36myiTkDzLwEJQSCR0h9ieO2aZtOTgkGUHLLW1dbl1+/1pbONVW3LdM2F6mv4dDLx4kF3RhhV+z7w3zaIGtyrBsCvkmWJQu1TJlmGUDqVYC3q9zuE6relyVxcBRujactOm2oY4UTnOD7IMhbv6xTHDNC5JFKislk1c4dIcCXwTVvNZgd99aibrxXY6p+9bqNPzIi3VaRjS73BV6z+7y15G/5wiQlGnFBcoNygSYd8cz2cfW0GX2Dzc7sLU8TNRvINqrdUZYZ80JwqLmrLnuBiy8ngdwKO9HlCOXbNniiK9UZXjZPBIlIIt3JH95YPCI2E7OvxxonRoZIFXIyZlc6eLdji6gpyw7bOtT83puFZz3UlB/6KYkqjI7gj3RzcgCLwpjx9H0cwjuQQHYaSd5/E6Vp7N2rQpZ3JmMZrpIyDkwVI7dMOK4hHS4f0ljCPqh4ccFWxcOGg+JFNf0RZaUKo4k8+C1h2jcnxYmvBWX/J8XKHrOpE3DTjMnSdRD+xQ0QcRP44R5nKIs7y/1aW6kO90RvwteS/R0fq6D+3U6EdJVHxtEqrrCyHV60Aly6In0zAD9G2gpsQ1Z9FeSM3
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

