apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "13.0.0"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: netbird
  namespace: argocd
spec:
  destination:
    namespace: netbird
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/netbird
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/netbird/argocd-apps/values-netbird.yaml
    - repoURL: https://github.com/ashish1099/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
