apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCYtKsOAhoqDV7I6R+Pd3S3DKd4wz3f9i8mEM3I4wMAG7R4Ln0vjvK2vqv07hZjpq09WDIJolcjFYzuJoR5/mE4Vbb2Qiu4UZMxFWcaAap0m2lSu7R5EsjI8OgsFCKG3YywhTXtM1tK+NOfA2mqlN87LQsQmh6MfIcR4BSMT5mitfWtW4c3sRQRWJfmAhPkeqPRaJO2z7J6ChHhKA49OOn1V/X4nrEayl98OQbbnVHJeQKzhgxztOa/+Zfa5o5WB7J2DuE3ETywBw++mh/JT7N/xG67HvS6m6i6rOHomX7cjDnfO8muNJ/Dt5kutHpZHNnFN25fzpMH/4l3JcPvGc5U0peYDcRganqkZQRVc/TSOsCVRfr/vsgBzFdBFV+P+a1PymTGw2hmhcD7Szjlesb4NeHAGPm+rkcg7ITd0TNj82R4Qa6d0iHBqEd0hNqYH320AOVXTNZwWzz4XrazY6tnNlhk4dm9P9jK9ZIxK1pyTy5bh+8+GkYRCT4BfeJmmKxAzR8rWcrcNcDJmEKBPB4lHfsKKziA5dT8xXQsfWzqTXSDCk0oeB0H3uO82wbI7PF26yQpbNXk7bh6icbJ6ts9huvX8uiJD2OTCHNTy4Cicmcl3cGLuTBDx3yfkhmh/K7Vq3gIYgpIygPkzbXbjLtipB3wzUegIk3Ub6Cdj73gUaCqJVFZO2K67/DOqvGCtjzhv+++o47b/7mvGHdu1YGN5jo82Bi15xkKYAXNpOxBnUx5zMvac/7HMiQKAdDhtmHhy5ghITyWUP8jLZjYLRTp
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

