apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 16.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "1"
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: kubeaid
  source:
    path: k8s/kubeaid-kds-demo/argocd-apps
    repoURL: https://github.com/ashish1099/kubeaid-config
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
