apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 16.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  source:
    path: k8s/kubeaid-kds-demo/sealed-secrets
    repoURL: https://github.com/ashish1099/kubeaid-config
    targetRevision: HEAD
    directory:
      recurse: true
